config/routes.rb
Rails.application.routes.draw do
  get 'pieces/edit'

  get 'pieces/update'

  get 'pieces/show'

  get 'pieces/new'

  get 'pieces/create'

  get 'errors/not_found'

  get 'errors/internal_server_error'

  get 'personal_messages/create'

  get 'conversations/index'

  get 'conversations/show'

  devise_for :users
  resources :projects
  resources :pieces, only: [:destroy]
  resources :roles do
    resources :requests, only: :new
  end
  resources :requests, except: :new do
    post :decline, on: :member
    post :accept, on: :member
  end
  get 'dashboard' => 'dashboards#show'
  resources :users do
    get :invite, on: :member
  end
  root to: 'pages#home'
  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :profile_picture, PhotoUploader
  has_many :request_collaborator, :class_name => 'Request', :foreign_key => 'user_id'
  has_many :created_requests, :class_name => 'Request', :foreign_key => 'created_by_id'

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pieces
  accepts_nested_attributes_for :pieces

  has_many :projects
  has_many :requests, through: :projects
  validates :email, uniqueness: true

  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'
  has_many :personal_messages, dependent: :destroy
  # TODO
  # validates :first_name, presence: true
  # validates :last_name, presence: true

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def outgoing_invites
    self.created_requests.select { |request| request.user != self}
  end

  def outgoing_requests
    self.created_requests.select { |request| request.user == self}
  end

  def incoming_invites
    self.request_collaborator.select { |request| request.created_by != self }
  end

  def incoming_requests
    self.requests.select { |request| request.created_by != self }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  skip_after_action :verify_authorized
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    user_params
    @user = current_user
    @user.update(user_params)
    # @user.pieces.build
    # if @user.update(user_params)
    #   p params[:pieces]['cloudinary_path']
    #   params[:pieces]['original_filename'].each do |cl_path|
    #     if @user.pieces.where(cloudinary_path: cl_path).nil?
    #       @piece = @user.pieces.create(cl_path: cl_path)
    #     end
    #   end
    # end
    if @user.save!
      redirect_to dashboard_path(@user)
    else
      render 'new'
    end
    # redirect_to edit_user_path(@user)
  end

  def invite
    @request = Request.new
    @request.user = User.find(params[:id])
    @request.owner_confirm = true
    @request.created_by = current_user
    @request.role.project = Project.where()
  end

  private

  # def piece_params
  #   params.require(:piece).permit(:title, :description, :cloudinary_path, :cloudinary_path_cache)
  # end

  def user_params
    params.require(:user).permit(:profile_picture, :profile_picture_cache, :bio, :email, :password, :skills, :portfolio_url, :first_name, :last_name, pieces_attributes: [:cloudinary_path])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
    <div class="profile-form">
      <div class="row">
        <div class="col-lg-12 profile-form-header">
          <h2>Edit your Profile</h2>

      </div>
      <%= simple_form_for @user, html: { id: "user-form"} do |f| %>

        <%= f.input :profile_picture %>

        <%= f.input :profile_picture_cache, as: :hidden %>

        <%= f.text_field :first_name, placeholder: 'first name', label:false%>

        <%= f.text_field :last_name, placecholder: 'last name', label:false %>

        <%= f.text_field :bio, placeholder: 'bio', label:false %>

        <%= f.text_field :skills, placeholder: 'skills', label:false %>

        <%= f.text_field :portfolio_url, placeholder: 'portfolio url', label:false %>

<!--         <%= simple_fields_for :pieces do |p| %>
          <%= p.label "upload files" %><br>
          <%= p.file_field :cloudinary_path, :multiple => true %> -->

        <%= f.button :submit, "update profile", class: "btn" %>
<!--         <% end %> -->
      <% end %>
<!-- uncomment to work on user portfolio -->
<!--       <div class="portfolio">
        <h2>Your Portfolio</h2>
        <% unless @user.pieces.nil? %>
          <%= @user.pieces.each do |piece| %>
            <div class="portfolio-piece" id="#piece-card-<%= piece.id %>">
            <%= p piece %>
              <%= cl_image_tag piece.cloudinary_path %>
              <%= link_to "edit", edit_piece_path(piece), class: "btn"%>
              <%= link_to 'delete', piece_path(piece),
                data: {:confirm => 'Are you sure?'}, :method => :delete, remote: :true %>
            </div>
          <% end %>
        <% end %>

      </div> -->

<!--       <button id= "add"><%= link_to "add another file", pieces_new_path(@user.pieces.new) %></button> -->
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">

  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/invite.html.erb
<div class="container">
  <div class="invite-user">
    <div class="invite-user-header">
      <h1>Invite <%= @request.user.first_name %> to Join your Project</h1>
    </div>
    <div class="request-user-details">
      <p><%= @request.user.first_name %></p>
      <p><%= @request.user.skills %></p>
    </div>
    <%= simple_form_for [@role, @request] do |f| %>
      <div class="request-project-and-role">
        <!-- add js dropdown for which project and role -->
        <%= f.text_field :project %>
        <%= f.text_field :role %>
      </div>
      <div class="request-invite-message">
        <%= f.text_field :owner_message %>
      </div>
      <div class="invite-create-or-back">
        <button class="btn"><%= link_to "Back", user_path(@request.user) %></button>
        <%= f.button :submit, 'submit request', class: "btn" %>
      </div>
      <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row dashboard-total">
    <div class="profile-card col-md-3">
      <div class="profile-picture">
         <% if @user.profile_picture %>
           <div class="card-img bg-picture" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.2) 0%, rgba(0,36,61,0.2) 30%), url( <%= @user.profile_picture %>);">
           </div>
    <!-- <%= cl_image_tag @user.profile_picture %> -->
         <% else %>
           <div class="card-img bg-picture" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.2) 0%, rgba(0,36,61,0.2) 30%), url('default-user.png');">
           </div>
         <% end %>

        <div class="dash-profile-info">
          <h2 class="username"><%= @user.first_name %> <%= @user.last_name %></h2>
          <p class="user-bio"><%= @user.bio %></p>
          <h4>Skills</h4>
          <p><%= @user.skills %></p>
          <h4>Portfolio</h4>
          <p><%= link_to "my portfolio", "http://#{@user.portfolio_url}" %></p>
<!--           <% if @user != current_user %>
          <%= link_to "invite #{@user.first_name}", invite_user_path(@user) %>
          <% end %> -->

          <% if current_user == @user %>
            <%= link_to edit_user_path(@user) do %>
              <p class="edit-profile-link text-center" id="edit">edit profile</p>
            <% end %>
            <% else %>
              <%= link_to new_personal_message_path(receiver_id: @user.id) do %>
                <p class="edit-profile-link text-center" id="edit">send a message</p>
              <% end %>
              <% end %>
        </div>
        </div>
      </div>

      <div class="col-md-8 col-md-offset-1 ">
        <div class="active-projects">
          <h1 class="project-title">Projects</h1>
          <div class="row">
          <% @user.projects.each do |project| %>
            <div class="col-md-6">
              <%= link_to project_path(project.id) do %>
              <div class="card">
                <div class="card-img" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.2) 0%, rgba(0,36,61,0.2) 30%), url( <%= project.picture %>);">
                </div>
                <div class="card-content">
                  <h4 class="card-title"><%= project.title %></h4>
                  <h4 class="card-category"><%= project.category %></h4>
                  <h5 class="card-subcategory subcategory"><%= project.subcategory %></h5>
                  <p class="project-description"><%= project.short_description %></p>
                </div>
              <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>