config/routes.rb
Rails.application.routes.draw do
  get 'pieces/edit'

  get 'pieces/update'

  get 'pieces/show'

  get 'pieces/new'

  get 'pieces/create'

  get 'errors/not_found'

  get 'errors/internal_server_error'

  get 'personal_messages/create'

  get 'conversations/index'

  get 'conversations/show'

  devise_for :users
  resources :projects
  resources :pieces, only: [:destroy]
  resources :roles do
    resources :requests, only: :new
  end
  resources :requests, except: :new do
    post :decline, on: :member
    post :accept, on: :member
  end
  get 'dashboard' => 'dashboards#show'
  resources :users do
    get :invite, on: :member
  end
  root to: 'pages#home'
  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- FOOTER -->
<div class="footer-container">
  <div id="footer-black">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-4">
          <ul class="list-inline">
            <li><a href="https://www.facebook.com"><i class="fa fa-facebook" target="blank"></i></a></li>
            <li><a href="https://www.instagram.com"><i class="fa fa-instagram" target="blank"></i></a></li>
            <li><a href="https://www.youtube.com"><i class="fa fa-youtube" target="blank"></i></a></li>
            <li><a href="https://www.twitter.com"><i class="fa fa-twitter" target="blank"></i></a></li>
          </ul>
        </div>
        <div class="col-xs-8 text-right">
          <p>©zentangle</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "zentangle_50px.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
<!--     <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>
    <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to "create a project", new_project_path %>
    </div>
      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.profile_picture || "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "profile", user_path(current_user) %></li>
          <li><%= link_to "dashboard", dashboard_path %></li>
          <li><%= link_to "messages", conversations_index_path %></li>
          <li id="logout"><%= link_to "log out", destroy_user_session_path, method: "delete" %></li>
        </ul>
        </div>
      </div>

    <% else %>

      <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
<!--     <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %> -->
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_pusher.html.erb
<div class="pusher">

  <div class="hidden accepted-request-notification">
    <h2>Your request was accepted</h2>
  </div>

  <div class="hidden declined-request-notification">
    <h2>Your request was declined</h2>
  </div>

</div>