config/routes.rb
Rails.application.routes.draw do
  get 'pieces/edit'

  get 'pieces/update'

  get 'pieces/show'

  get 'pieces/new'

  get 'pieces/create'

  get 'errors/not_found'

  get 'errors/internal_server_error'

  get 'personal_messages/create'

  get 'conversations/index'

  get 'conversations/show'

  devise_for :users
  resources :projects
  resources :pieces, only: [:destroy]
  resources :roles do
    resources :requests, only: :new
  end
  resources :requests, except: :new do
    post :decline, on: :member
    post :accept, on: :member
  end
  get 'dashboard' => 'dashboards#show'
  resources :users do
    get :invite, on: :member
  end
  root to: 'pages#home'
  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/models/request.rb
class Request < ApplicationRecord
  attr_reader :message
  belongs_to :created_by, :class_name => "User"
  belongs_to :user, :class_name => "User"
  # belongs_to :user
  belongs_to :role

  # validates :user_confirm, presence: true #nil is pending, false is declined
  # validates :owner_confirm, presence: true #nil is pending, false is declined
  # validates :owner_message, presence: true
  # validates :user_message, presence: true
  validates :created_by, presence: true



  def status(current_user)
    @request = self
    @role = @request.role
    if @role.project.owner == current_user
      owner_status_logic
    elsif @request.user == current_user
      user_status_logic
    end
  end

  private

  def owner_status_logic
    if @request.created_by == @request.role.project.owner
      # you invited user
      if @request.user_confirm
        @message = "#{@request.user.full_name} joined #{@role.project.title}!"
      elsif @request.user_confirm == false
        @message = "#{@request.user.full_name} declined your request to join #{@role.project.title}"
      else
        @message = "You requested #{@request.user.full_name} to join #{@role.project.title}"
      end
    else
      # user requested to join your project
      @message = "#{@request.user.full_name} requested to join #{@role.project.title}!"
      @message = "You declined #{@request.user.full_name}'s request to join #{@role.project.title}" if @request.owner_confirm == false
    end
  end

  def user_status_logic
    if @request.created_by == @request.user
      # you requested to join owner's project
      @message = "You requested to join"
      @message = "#{@role.project.owner.full_name} declined your request to join #{@role.project.title}" if @request.owner_confirm == false

    else
      # owner invited you to join their project
      if @request.user_confirm
        @message = "You joined #{@role.project}!"
      elsif @request.user_confirm == false
        "#You declined {@role.owner.full_name}'s request for you to join #{@role.project.title}!"
      else
        @message = "#{@role.owner.full_name} requested you to join #{@role.project.title}!"
      end
    end
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_role, only: []
  before_action :set_request, only: [:show, :edit, :update, :destroy, :accept]
  skip_after_action :verify_authorized
  def index
    authorize @request
    @request = Request.all
  end

  def show
    @request = Request.find(params[:id])
    @role = @request.role
    @request.status(current_user)
  end

  def new
    @request = Request.new
    @role = Role.find(params[:role_id])
    @request.role = @role
    @request.user_confirm = true
    @request.created_by = current_user
    authorize @request
  end

  def create
    @request = Request.new(request_params)
    @request.created_by = current_user
    @request.user = current_user
    authorize @request
    @request.save
    if @request.save!
      redirect_to dashboard_path
    else
      redirect_to new_role_request_path(@request.role)
      # path unclear
    end
  end

  def decline
    authorize @request
    if current_user == @request.project.owner
      @request.owner_confirm == false
      Pusher.trigger("user-#{@request.user.id}-#{Rails.env}", 'status', {
        message: "Your request to join #{@request.role.project.title} was declined :("
    })
    else
      @request.user_confirm == false
      Pusher.trigger("user-#{@request.user.id}-#{Rails.env}", 'status', {
        message: "Your request to join #{@request.role.project.title} was declined :("
      })
    end

  end

  def accept
    Pusher.trigger("user-#{@request.user.id}-#{Rails.env}", 'status', {
      message: "accept"
    })
    authorize @request

    @request.user_confirm = true
    @request.owner_confirm = true
    @request.save

    #"#{@request.role.project.owner.first_name} accepted your request to join #{@request.role.project.title}"
    redirect_to dashboard_path
  end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy
  end

  def update
    @request = Request.find(params[:id])
    params[:commit] =="accept" ? @request.owner_confirm = true : @request.owner_confirm = false
    @request.destroy if params[:commit] == "decline"
    redirect_to dashboard_path
  end

  private

  def set_role
    @role = Role.find(params[:role_id])
  end

  def set_request
    @request = Request.find(params[:id])
    authorize @request
  end

  def request_params
    params.require(:request).permit(:user_confirm, :owner_confirm, :user_message, :owner_message, :created_by, :role_id, :project_id)
  end
end

app/views/requests/index.html.erb
<h1>Requests#index</h1>
<p>Find me in app/views/requests/index.html.erb</p>

app/views/requests/new.html.erb
<div class="container">
  <div class="request-to-join">
    <div class="row">
      <div class="col-xs-12 col-md-10 col-md-offset-1">
        <div class="request-to-join-header text-center">
          <h1>Apply for role</h1>

        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-5 col-md-offset-1">
        <div class="request-project-details">
          <h2><%= @role.project.title %></h2>
          <h3>about the project</h3>
          <p><%= @role.project.short_description %></p>
          <%= simple_form_for @request do |f| %>
          <h3>Role: <%= @role.title %></h3>
          <p><%= @role.description %></p>
        </div>
      </div>
      <div class="col-xs-12 col-md-5 col-md-offset-1">
        <div class="right-col">
          <h3>Requirements</h3>
          <p><%= @role.requirements %></p>
          <h3>Compensation</h3>
          <p><%= @role.compensation %></p>
          <div class="request-role-message">
            <%= f.text_area :user_message, placeholder: "How can you contribute to the project?" %>
            <%= f.input :role_id, as: :hidden %>
            <%= f.input :user_confirm, as: :hidden %>
          </div>
          <div class="request-create-or-back">
            <button class="btn back-btn"><%= link_to "Back", project_path(@role.project) %></button>
            <%= f.button :submit, 'submit request', class: "btn request-btn" %>
          </div>
        </div>
      </div>

    </div>


    <%end %>
  </div>
</div>

app/views/requests/show.html.erb
<div class="container">
  <div class="requested-body">
    <div class="row">
      <div class="col-xs-12">
        <div class="request-to-join-header text-center">
          <!-- <h1>You requested to join</h1> -->
          <h1><%= @request.message %></h1>
          <!--  -->
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-5 col-md-offset-1">
        <div class="request-project-details">
         <h2><%= @request.role.project.title %></h2>
         <h3>about the project</h3>
         <p><%= @role.project.short_description %></p>
         <% unless current_user == @role.project.owner %>
         <button class="btn popup-btn"><%= link_to "learn more", project_path(@role.project) %></button>
         <% end %>
       </div>
       <div class="request-project-details">
        <% unless current_user == @request.user %>
        <h2>Collaborator: <%= @request.user.full_name %></h2>
        <h3>Bio</h3>
        <p><%= @request.user.bio %></p>
        <h3>Skills</h3>
          <p><%= @request.user.skills %></p>
          <button class="btn popup-btn"><%= link_to "learn more", user_path(@request.user) %></button>
          <% end %>
        </div>
      </div>

    <div class="col-xs-12 col-md-5 col-md-offset-1">
      <%= simple_form_for [@request], :html => {:id=>'requested-form'} do |f| %>
      <div class="request-project-details">
        <h2>Role: <%= @role.title %></h2>
        <h3>Description</h3>
        <p><%= @role.description %></p>
        <h3>Requirements</h3>
          <p><%= @role.requirements %></p>
          <h3>Compensation:</h3>
          <p><%= @role.compensation %></p>
        </div>
        <div class="requested-messages">
          <% if @request.created_by == @role.project.owner %>
          <div class="request-project-details">
          <h3>Message</h3>
            <p><%= "#{@role.project.owner.first_name}: #{@request.owner_message}" %> </p>
          </div>
  <!--           <% if @request.user_message.nil? %>
              <div class="requested-send-message">
                <%= f.text_field :user_message %>
                <%= link_to 'send', "", :onclick => "$('#requested-form').submit()" %>
              </div>
            <% else %>
              <div class="requested-sent-messsage">
                <p><%= "#{@role.user.first_name}: #{@request.user_message}" %> </p>
              </div>
              <% end %> -->

              <% else %>
              <div class="request-project-details">
              <h3>Message</h3>
                <p> <strong><%= @request.created_by.first_name %>:</strong> <%= @request.user_message %> </p>
              </div>
  <!--           <% if @request.owner_message.nil? %>
              <% if @request.role.project.owner == current_user %>
                <div class="requested-send-message">
                  <%= f.text_field :owner_message %>
                  <%= link_to 'send', "", :onclick => "$('#requested-form').submit()" %>
                </div>
              <% end %>

            <% else %>
              <p><%= "#{@role.project.owner.first_name}: #{@request.owner_message}" %> </p>
              <% end %> -->
              <% end %>
            </div>


            <div class="row">



            <!-- implement message thread table -->
            <div class="message-button">
              <% if @request.user == current_user %>
              <button class="msg-btn"><%= link_to 'send a message', new_personal_message_path(receiver_id: @request.role.project.owner.id) %></button>

              <% else %>
              <button class="msg-btn"><%= link_to 'send a message', new_personal_message_path(receiver_id: @request.user.id) %></button>
              <% end %>



              <button class="btn popup-btn btn-margin"><%= link_to "Back", dashboard_path %></button>
              <% unless (@request.user_confirm && @request.owner_confirm) || current_user == @request.created_by %>
              <% f.button :submit, 'decline', class: "btn" %>

              <% f.button :submit, 'accept', class: "btn" %>

              <%= link_to "ACCEPT", accept_request_path(@request), method: :post%>
              <% end %>
            </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>