config/routes.rb
Rails.application.routes.draw do
  get 'pieces/edit'

  get 'pieces/update'

  get 'pieces/show'

  get 'pieces/new'

  get 'pieces/create'

  get 'errors/not_found'

  get 'errors/internal_server_error'

  get 'personal_messages/create'

  get 'conversations/index'

  get 'conversations/show'

  devise_for :users
  resources :projects
  resources :pieces, only: [:destroy]
  resources :roles do
    resources :requests, only: :new
  end
  resources :requests, except: :new do
    post :decline, on: :member
    post :accept, on: :member
  end
  get 'dashboard' => 'dashboards#show'
  resources :users do
    get :invite, on: :member
  end
  root to: 'pages#home'
  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  skip_after_action :verify_authorized
  def show
    @user = current_user
    @projects = @user.projects
    @requests = Request.where(user: current_user)
  end

  private

  def request_status(request)
    if request.user_confirm && request.owner_confirm
      return "joined"
    elsif request.user_confirm.nil? || request.owner_confirm.nil?
      return "pending"
    elsif !request.user_confirm || !request.owner_confirm
      return "declined"
    end
  end

  helper_method :request_status
end

app/views/dashboards/_main.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-1 col-md-3">
      <div class="profile-card">
        <div class="profile-picture bg-picture">
           <% if @user.profile_picture %>
            <%= cl_image_tag @user.profile_picture %>
            <% else %>
            <%= image_tag "default-user.png", width: 100%>
            <% end %>
        </div>
        <div class="profile-info">
          <h2><%= @user.first_name %> <%= @user.last_name %></h2>
          <p><%= @user.bio %></p>
          <h4>Skills</h4>
          <p><%= @user.skills %></p>
          <h4>Portfolio</h4>
          <p><%= link_to "my portfolio", "http://#{@user.portfolio_url}" %></p>
        </div>
        <%= link_to "edit", edit_user_path(@user) %>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/_my_projects.html.erb
<div class="container">
  <div class="wrapper">


    <div class="row">
      <% @projects.each do |project| %>
      <div id="dashboard-card-<%= project.id %>">
        <div class="col-xs-12 col-sm-6 col-md-4">
          <%= link_to project_path(project.id) do%>
          <div class="card">
            <div class="card-img bg-picture"" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.4) 0%, rgba(0,36,61,0.4) 30%), url( <%= project.picture %>);">
            </div>
            <div class="card-content">
              <h3 class="card-title"><%= project.title %></h3>
              <h4 class="card-category"><%= project.category %></h4>
              <h5 class="card-subcategory dash-subcategory"><%= project.subcategory %></h5>
              <p class="card-description dash-description"><%= project.short_description %></p>
                <div class="card-btns">
                  <%= link_to "edit", edit_project_path(project), class: "btn btn-edit"%>
                  <%= link_to 'delete', project_path(project),
                  data: {:confirm => 'Are you sure?'}, :method => :delete, remote: :true, class: "btn btn-delete" %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/dashboards/_requests.html.erb
<div class="container">
  <div class="wrapper">


    <div class="row requests">
      <% requests.each do |request| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="request-card">
          <%= link_to request_path(request) do %>
          <div class="request-card-img bg-picture" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.4) 0%, rgba(0,36,61,0.4) 30%), url( <%= request.role.project.picture %>);">
          </div>
          <div class="request-card-content">
            <h3 class="request-card-subcategory"><%= request.role.title %></h3>
            <h5 class="request-card-title"><%= request.role.project.title %></h5>
            <div class=<%= request_status(request) %>> <p> status: <%= request_status(request) %></p></div>
          </div>
        </div>

        <% end %>
      </div>
      <% end %>
  </div>

  <div class="row invites">
    <% invites.each do |request| %>
    <div class="request-card">
      <div class="col-xs-12 col-sm-6 col-md-4">
        <%= link_to request_path(request) do %>
        <div class="user-requests-div" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.4) 0%, rgba(0,36,61,0.4) 30%), url( <%= request.role.project.picture %>);"></div>
          <div class="user-requests-content">
            <h3><%= request.role.title %></h3>
            <h5><%= request.role.project.title %></h5>
            <div class=<%= request_status(request) %>><%= request_status(request) %></div>
          </div>
        </div>

        <% end %>
      </div>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboards/show.html.erb
<div class="container">
  <div class="row dashboard-total">

    <div class="profile-card col-md-3">
      <div class="profile-picture">
        <% if @user.profile_picture %>
          <div class="card-img bg-picture" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.2) 0%, rgba(0,36,61,0.2) 30%), url( <%= @user.profile_picture %>);">
          </div>
   <!-- <%= cl_image_tag @user.profile_picture %> -->
        <% else %>
          <div class="card-img bg-picture" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.2) 0%, rgba(0,36,61,0.2) 30%), url('default-user.png');">
          </div>
        <% end %>
      </div>
      <div class="dash-profile-info">
        <h2 class="user-name"><%= @user.first_name %> <%= @user.last_name %></h2>
        <p class="user-bio"><%= @user.bio %></p>
        <h4>Skills</h4>
        <p><%= @user.skills %></p>
        <h4>Portfolio</h4>
        <p><%= link_to "Behance", "http://#{@user.portfolio_url}" %></p>

      <!-- <p class="edit-profile-link text-center" id="edit"> -->
        <%= link_to edit_user_path(@user) do %>
          <p class="edit-profile-link text-center" id="edit">edit profile</p>
        <% end %>
        </div>
      <!-- </p> -->
    </div>

  <div class="col-md-8 col-md-offset-1 ">
  <!-- MY REQUESTS -->
    <div class="dash-box-right">
      <div class="dash-projects-title">
        <h2 class="dash-box-title">My Requests</h2>
      </div>

    <% if @requests.first.nil? %>
      <h5 class="no-requests">You have no applications. Search for projects and apply!</h5>
    <% else %>
      <% @requests.each do |request| %>
        <%= link_to request_path(request) do  %>
          <div class="row my-projects-list">
            <hr>
            <div class="col-md-3 dash-project-picture">
              <!-- PROJECT PICTURE HERE -->
              <div class="card-img bg-picture" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.2) 0%, rgba(0,36,61,0.2) 30%), url( <%= request.role.project.picture %>); height: 100px;">
              </div>
            </div>
            <div class="col-md-6 dash-project-info">
              <!-- PROJECT INFO HERE -->
              <h3 class="card-title" id="request-title"><%= request.role.project.title %></h3>
              <h5 class="card-subcategory dash-sub"> <strong> <%= request.role.title %></strong> </h5>
              <!-- <p class="card-description dash-description"><%= request.role.description %></p> -->
            </div>
            <div class="col-md-3 dash-project-status">
              <!-- PROJECT STATUS HERE -->
              <div class="<%= request_status(request) %>">
                <p> status: <%= request_status(request) %></p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
    </div>

<!-- END OF MY REQUESTS -->

<!-- MY PROJECTS -->
    <div class="dash-box-right dash-requests">
      <div class="dash-projects-title">
        <h2 class="dash-box-title">My Projects</h2>
      </div>
      <% if @projects.first.nil? %>
        <h5 class="no-requests">You have no projects. Create one now!!</h5>
        <% else %>
      <% @projects.each do |project| %>
        <%= link_to project_path(project) do %>
          <div class="row my-projects-list">
            <hr>
            <div class="col-md-3 dash-project-picture">
              <!-- PROJECT PICTURE HERE -->
              <div class="card-img bg-picture" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.2) 0%, rgba(0,36,61,0.2) 30%), url( <%= project.picture %>); height: 100px;"> </div>
            </div>
            <div class="col-md-6 dash-project-info">
              <!-- PROJECT INFO HERE -->
              <h3 class="card-title"><%= project.title %></h3>
              <h5 class="card-subcategory dash-sub"> <strong> <%= project.category %></strong> <%= project.subcategory %></h5>
              <p class="card-description dash-description"><%= project.short_description %></p>
            </div>
            <div class="col-md-3 dash-project-status">
              <!-- PROJECT STATUS HERE -->
              <h2 class="dash-pending-request">PENDING REQUESTS</h2>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <% end %>
  </div>
<!-- END OF MY PROJECTS -->

  </div>
</div>


<%= content_for(:after_js) do %>
  <script>

    var pusher = new Pusher('b0de02a8f3fdb48196e8', {
      cluster: 'eu',
      encrypted: true
    });

    var channel = pusher.subscribe("user-<%= @user.id %>-<%= Rails.env %>");
    channel.bind('status', function(data) {
      location.reload();
    });

  </script>
<% end %>